### PR TITLE
Trying remove high contrast element from light themes

### PR DESCRIPTION
**Pull request by mpstv**
## Purpose
Removing high contrast elements from light themes
## What
Trying remove high contrast elements from light themes and make it more like light theme version 1.3.0

Result looks like:

light_theme_fixes

## How to Test
Run extension and change theme to "Winter is Coming (Light) / Winter is Coming (Light - No Italics)".

## What to Check
Verify that changes has been added correctly.
Related with #42 and maybe #41

### CODE REVIEW

**Comment by mpstv** [comment]
@johnpapa can you review this pull request?

**Comment by johnpapa** [comment]
Hi. Im game for some changes to this light theme set. Instead of removing them, can they be changed?

Also, can you show a before and after image of the changes in play?

**Comment by mpstv** [comment]
I changed this pull request and now:

before

image

after

image

**Comment by johnpapa** [comment]
Are the only changes really noticeable on the explorer? Are there no font color changes ?

**Pull request merged**
