### PR TITLE
Add dark black theme without italics

### PR DESCRIPTION
**Pull request by jaumecapdevila**
## Purpose
* Allow disabling italics for the dark black theme

## What
* Add a new theme

## How to Test
* Activate the new theme

## What to Check
Verify that the following are valid
* Colors for the dark black theme are the same
* Italics are gone

### CODE REVIEW

**Comment by jaumecapdevila** [comment]
First of all, thanks for this awesome theme, I love the _dark black_ version of it 😄. The only drawback is that I do not like italics that much, so that's why I would like to do this contribution.

**Comment by johnpapa** [comment]
Thanks. Did you just copy the black one and remove all italics settings? If so, that sounds about right.

I had removed the black ones for a while due to maintenance issues. I would love a way to make them share most of the same colors. Barring that, this could become a problem again the future :(

**Comment by jaumecapdevila** [comment]
Yep, I've just duplicated the dark one an removed all the italic settings.

Regarding the maintenance problems, have you tried/investigated any way to share the settings between themes, that I can take a look?

**Comment by johnpapa** [comment]
Thanks for confirming. I'll review this today.

I havent had time on that - if you can look into it, I'd be very grateful.

**Pull request merged**
