### PR TITLE
Add classic light theme

### PR DESCRIPTION
**Pull request by mpstv**
A lot of people really like the light theme of version 1.3.0. 
To make it possible to use, I forked Winter Is Coming and published on the [marketplace](https://marketplace.visualstudio.com/items?itemName=mpstv.winterislight).
What do you think of the inclusion of this theme in Winter Is Coming?

## Purpose
Include the classic light themes in Winter Is Coming.

## What
Add two classic light themes (italic and non-italic options).

## How to Test
Run extension and change theme to "Winter is Coming (Light Classic) / Winter is Coming (Light Classic - No Italics)".

## What to Check
Verify that changes has been added correctly.

Related with #41 and #42

### CODE REVIEW

**Comment by mpstv** [comment]
Hi, @johnpapa. Please say your opinion about this proposal.
Primary i created a fork, but after that, i thought that many people want use this theme like a part of Winter Is Coming.
What do you think?

**Comment by johnpapa** [comment]
hi - there is currently a light theme with and without italics. If you have proposals for a change to them, can you make an issue and we can discuss the changes?

if I misunderstand , please let me know

**Comment by mpstv** [comment]
@johnpapa thanks for feedback.
This is an proposal to return the light theme version 1.3.0. It different by color scheme for the code and workspace.
Two themes in this request are taken from [PR 36](https://github.com/johnpapa/vscode-winteriscoming/pull/35) and [PR 35](https://github.com/johnpapa/vscode-winteriscoming/pull/36). I suggest giving a choice which theme to use: the current light theme or the classic light theme (version 1.3.0), because many people use light themes and like version 1.3.0.

**Comment by oieduardorabelo** [comment]
perhaps these can help highlight the current frustration,

### current version 1.4.1
1 4 1-b
1 4 1-a

### version 1.3.1
1 3 1-a
1 3 1-b


perhaps is just something "wrongly styling" the sidebar "section bar" and the file "tab name" ?

**Comment by mpstv** [comment]
@oieduardorabelo thanks for your comment.
I trying do this in [PR 44](https://github.com/johnpapa/vscode-winteriscoming/pull/44), and you can review it. It seems to me, it has turned out not bad :)

So, we have a two path:
1) Include classic light themes in Winter Is Coming.
2) Changes existing light themes.

I think that both variants make happy light theme lovers :)

**Comment by johnpapa** [comment]
I suggested that you propose changes to the existing light themes and if we agree you can make a pull request for review. 

Closing this one as it adds themes.

**Pull request closed without merging**
